### ISSUE TITLE
Вопросы с лекции: функции-расширения; inline-функции; рефлексия; корутины

### ISSUE THREAD

**Issue by VladislavPraskov** [mipt-npm/mipt-kotlin-integration#7]

**Comment by altavir** [comment]
А можно разделить это на куски? В одну лекцию явно все не вместится.

**Comment by VladislavPraskov** [comment]
Ну разумеется. Вы просто сказали писать всё и сразу, вот. И там не
получилось label поставить, не было функции

сб, 23 февр. 2019 г., 16:01 Alexander Nozik <notifications@github.com>:

**Comment by VladislavPraskov** [comment]
Нужно разбить на несколько вопросов?

сб, 23 февр. 2019 г., 16:03 Владислав Прасков <vadislavpr@gmail.com>:

**Comment by altavir** [comment]
Сейчас сам сделаю

**Comment by altavir** [comment]
распихал
